version: 2

  
build:
  os: ubuntu-20.04
  tools:
    python: "3.12"

formats:
  - epub
  - pdf

sphinx:
  configuration: source/conf.py

python:
  install:
    - requirements: source/requirements.txt



commands:
  # Print installed packages after installing requirements
  - pip freeze
