name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - stable
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - stable

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-design sphinx-copybutton sphinx-togglebutton sphinx-tippy myst-parser sphinx_book_theme sphinx-rtd-theme rst2pdf
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Build docs
        run: |
          cd source
          # Create an empty __init__.py file in the _ext directory to make it a proper Python package
          touch _ext/__init__.py
          # Set PYTHONPATH to include the current directory so _ext can be found
          export PYTHONPATH=.:$PYTHONPATH
          sphinx-build -b html . build/html
          cd ..
          ls -la source/build/html  # Debug: List directory contents to verify files exist
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "source/build/html" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          routes_location: "/" # Location of routes.json file
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
