name: Azure Static Web App

on:
  push:
    branches:
      - stable
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - stable
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-design sphinx-copybutton sphinx-togglebutton sphinx-tippy myst-parser sphinx_book_theme sphinx-rtd-theme rst2pdf
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Build static directory for deployment
        run: |
          # Create a simple static directory for deployment
          mkdir -p build/html
          echo "<html><body><h1>CIT Services User Manual</h1><p>This is a placeholder page.</p></body></html>" > build/html/index.html
          # Copy your routes.json file to the output directory
          cp routes.json build/html/routes.json || true
          # Create a basic 404 page
          echo "<html><body><h1>404 - Page Not Found</h1><p>The page you requested could not be found.</p></body></html>" > build/html/404.html
          # List the build directory to confirm it exists
          ls -la build/html

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build/html" # App source code path - now from the root directory
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          routes_location: "/" # Location of routes.json file
          skip_app_build: true # Skip the build step as we built it manually

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
