name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - stable
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - stable

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      # Add Sphinx build steps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-design sphinx-copybutton sphinx-togglebutton sphinx-tippy myst-parser sphinx_book_theme rst2pdf
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Build Sphinx docs
        run: |
          # List directory structure before build
          echo "Current directory structure:"
          ls -la
          
          # Build the docs using the Makefile (which knows your project structure)
          make html
          
          # Check if build directory exists in standard location
          echo "Checking build directory locations:"
          ls -la build/html 2>/dev/null || echo "No build/html directory"
          ls -la source/_build/html 2>/dev/null || echo "No source/_build/html directory"
          
          # Create source/build/html directory and copy files there
          mkdir -p source/build/html
          
          # Copy from build/html if it exists
          if [ -d "build/html" ]; then
            echo "Copying from build/html to source/build/html"
            cp -r build/html/* source/build/html/
          # Otherwise copy from source/_build/html if it exists
          elif [ -d "source/_build/html" ]; then
            echo "Copying from source/_build/html to source/build/html"
            cp -r source/_build/html/* source/build/html/
          else
            echo "WARNING: Could not find any build output to copy to source/build/html!"
          fi
          
          # Copy routes.json to the build directory
          if [ -f "routes.json" ]; then
            echo "Copying routes.json to source/build/html"
            cp routes.json source/build/html/
          fi
          
          # Final check of build directory
          echo "Final build directory contents:"
          ls -la source/build/html || echo "Still no source/build/html directory!"
          
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_PLANT_0E077991E }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "source/build/html" # Changed to match Azure's expected location
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          routes_location: "/" # Added to include your routes config
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
